language: cpp
compiler:
  - gcc
  - clang
dist: bionic
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libssl-dev
      - libzmqpp-dev
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9C076FCC7AB8F2E43C2AB0E73241B9B7B4BD8F8E
  - echo "deb https://repos.iqrf.org/ubuntu bionic stable testing" | sudo tee /etc/apt/sources.list.d/iqrf.list
  - sudo apt-get update
  - sudo apt-get install libpaho-mqtt-dev
before_script:
  - mkdir deploy
  - git clone --recurse-submodules https://github.com/logimic/shape.git
  - cmake -Bshape-build -Hshape -DBUILD_TESTING:BOOL=true -DCMAKE_BUILD_TYPE=Debug -DSHAPE_DEPLOY:PATH=$PWD/deploy
  - cmake --build shape-build --target install
  - git submodule init
  - git submodule update
script:
  - cmake -Bshapeware-build -H. -Dshape_DIR:PATH=`pwd`/shape-build -DBUILD_ZEROMQ:BOOL=true -DBUILD_TESTING:BOOL=true -DCMAKE_BUILD_TYPE=Debug
  - cmake --build shapeware-build --target install
  - cd shapeware-build/ && ctest
matrix:
  allow_failures:
    - compiler: clang
